apiVersion: v1
kind: Template
metadata:
  name: candv_instant
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: candv
    name: candv
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: candv:latest
    resources: {}
    source:
      git:
        uri: https://github.com/dudash/candv
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:0.10
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: -RrzkM1YtNeJiy1Srreb
      type: GitHub
    - generic:
        secret: pWCEt6z5NQs2LQXnKMG1
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: candv
    name: candv
  spec:
    host: "${APPLICATION_DOMAIN}"
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: candv
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: candv
    name: candv
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: candv
      deploymentconfig: candv
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: candv
      template: mongodb-ephemeral-template
    name: mongodb
  spec:
    ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: mongodb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: candv
    name: candv
  spec:
    replicas: 1
    selector:
      app: candv
      deploymentconfig: candv
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: candv
          deploymentconfig: candv
      spec:
        containers:
        - env:
          - name: MONGODB_USER
            value: userSM1
          - name: MONGODB_PASSWORD
            value: NpIahJB8WVSrwIX2
          - name: MONGODB_DATABASE
            value: sampledb
          - name: MONGODB_ADMIN_PASSWORD
            value: HGrpyDm5P4PWEiDo
          image: candv
          imagePullPolicy: Always
          name: candv
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - candv
        from:
          kind: ImageStreamTag
          name: candv:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: candv
      template: mongodb-ephemeral-template
    name: mongodb
  spec:
    replicas: 1
    selector:
      name: mongodb
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: candv
          name: mongodb
      spec:
        containers:
        - env:
          - name: MONGODB_USER
            value: userSM1
          - name: MONGODB_PASSWORD
            value: NpIahJB8WVSrwIX2
          - name: MONGODB_DATABASE
            value: sampledb
          - name: MONGODB_ADMIN_PASSWORD
            value: HGrpyDm5P4PWEiDo
          image: mongodb
          imagePullPolicy: IfNotPresent
          name: mongodb
          ports:
          - containerPort: 27017
            protocol: TCP
          readinessProbe:
            initialDelaySeconds: 15
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          resources: {}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/mongodb/data
            name: mongodb-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: mongodb-data
    triggers:
    - imageChangeParams:
        containerNames:
        - mongodb
        from:
          kind: ImageStreamTag
          name: mongodb:latest
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: candv
    name: candv
parameters:
  - name: APPLICATION_DOMAIN 
    description: Custom hostname for service routes.  Leave blank for default hostname