swagger: '2.0'
info:
  version: 0.0.1
  title: CandV
  description: 'The CandV API'
basePath: /api/v0
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /boards:
    post:
      description: 'Add a new board'
      produces:
        - application/json
      responses:
        '200':
          description: 'add board successful'
          schema:
            title: NewBoardId
            items:
              $ref: '#/definitions/Identifier'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

  /boards/{boardId}:
    get:
      description: 'Returns the JSON for the entire clipboard'
      produces:
        - application/json
      parameters:
        - in: path
          name: boardId
          description: ID of item to fetch from the database
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: 'The list of all board items'
          schema:
            title: Items
            type: array
            items:
              $ref: '#/definitions/Item'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

  /boards/{boardId}/items:
    post:
      description: 'Add an item into this board'
      produces:
        - application/json
      parameters:
        - in: path
          name: boardId
          description: ID of board to add this item into
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: 'add item successful'
          schema:
            title: NewItemId
            items:
              $ref: '#/definitions/Identifier'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
 
  /boards/{boardId}/items/{itemId}:
    get:
      description: 'Returns the JSON for a specific item in a board'
      produces:
        - application/json
      parameters:
        - in: path
          name: boardId
          description: ID of board to fetch from the database
          required: true
          type: integer
          format: int64
        - in: path
          name: itemId
          description: ID of item to fetch from the database
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: 'The details about an item'
          schema:
            $ref: '#/definitions/Item'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: 'Removes the item from this board'
      produces:
        - application/json
      parameters:
        - in: path
          name: boardId
          description: ID of board to delete from
          required: true
          type: integer
          format: int64
        - in: path
          name: itemId
          description: ID of item to delete
          required: true
          type: integer
          format: int64
      responses:
        "204":
          description: pet deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Item:
    type: object
    properties:
      timestamp:
        type: string
        description: 'A timestamp of when the item was put in the clipboard as ISO 8601 e.g.: 2014-09-08T08:02:17-05:00'
      raw:
        type: string
        description: 'The raw string of the item on the clipboard'
  
  Identifier:
    type: integer
    description: 'An identifier for a board or item'
    
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
