swagger: '2.0'
info:
  version: 0.0.1
  title: CandV
  description: 'TODO The CandV API (ROUTES ARE NOT ALL DEFINED) YMMV'
paths:
  /:
    get:
      description: 'Returns the main webpage as HTML'
      produces:
        - text/html
      responses:
        '200':
          description: webpage
  /clipboard:
    get:
      description: 'Returns the full clipboard webpage as HTML'
      produces:
        - text/html
      responses:
        '200':
          description: webpage
  /paste:
    post:
      consumes:
        - application/x-www-form-urlencoded
      parameters:
          - name: pastedata
            description: 'The item to be added to the clipboard'
            required: true
            in: formData
            type: string
      responses:
        '200':
          description: OK
  /json/{itemId}:
    get:
      description: 'Returns the JSON for a specific item - TODO'
      produces:
        - text/json
      parameters:
        - in: path
          name: itemId
          description: ID of item to fetch from the database
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: 'The details about an item'
          schema:
            $ref: '#/definitions/Item'
  /json/clipboard:
    get:
      description: 'Returns the JSON for the entire clipboard - TODO'
      produces:
        - text/json
      responses:
        '200':
          description: 'The details for all clipboard items'
          schema:
            title: Items
            type: array
            items:
              $ref: '#/definitions/Item'
definitions:
  Item:
    type: object
    properties:
      timestamp:
        type: string
        description: 'A timestamp of when the item was put in the clipboard as ISO 8601 e.g.: 2014-09-08T08:02:17-05:00'
      raw:
        type: string
        description: 'The raw string of the item on the clipboard'
